export const ActionTypes = {

    SET_CITY: "SET_CITY",
    SET_CITY_NAME: "SET_CITY_NAME",
    ADD_TO_FAVORITES: "ADD_TO_FAVORITES",
    SET_FAVORITES: "SET_FAVORITES",
    TOGGLE_IS_SAVED: "TOGGLE_IS_SAVED",
    TOGGLE_DARK_MODE: "TOGGLE_DARK_MOD",
    

}